= PostgreSQL 9.3 Database Administration Volume 1 - Basic concepts 
Javier León (@jelitox) <jel1284@gmail.com>
v1.0, 2015-02-13
:toc:
:imagesdir: assets/images
:homepage: http://blog.javierleon.com.ve
:hp-tags: Blog,Personal
// Web page meta data.
:keywords: Blog, Javier León, IT, Devops, Desarrollo, Sysadmin, Social, Networks, emprendimiento, Pagina Oficial,
:description: Blog personal y Profesional, +
Ingeniero en Informatica, desarrollador y Administrador de Sistemas e infraestructura, +
Redes Sociales, facebook, instagram, twitter, pinterest +
proyectos de emprendimiento Freenlance, +
Pagina principal.

.{revdate}:  {revnumber} 
*******************************************************************


____
*******************************************************************
PostgreSQL 9.3.
------------
{description}

This book assumes the reader knows how to perform basic user operations such as connecting
to the database and creating tables.
The book covers the basic aspects of database administration from installation to cluster
management.
A couple of chapters are dedicated to the logical and physical structure in order to show
both sides of coin. The triplet of maintenance backup and restore completes the the picture,
not exhaustive but good enough to start getting “hands on” the product. The final chapter
is dedicated to the developers. The various sections are giving advice that can seem quite
3
obvious. But it’s better to repeat things than having dangerous mistakes when building an
application.

La internet de las cosas .

AsciiDoc is free software and is licenced under the terms of the 'GNU
General Public License version 2' (GPLv2).

TIP: The pages you are reading were written using AsciiDoc, to view
the corresponding AsciiDoc source click on the *Page Source* menu item
in the left hand margin.


:linkattrs:

== http://adf.ly/148zHH[Descargar , window="_blank"]


